name: keyboard_actions
description: Now you can add features to the Android / iOS keyboard in a very simple way. 
version: 2.1.2
author: Diego Velásquez <diego.velasquez.lopez@gmail.com>
homepage: https://github.com/diegoveloper/
repository: https://github.com/diegoveloper/flutter_keyboard_actions/

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
flutter:
